//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesForHandsMVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formatted_materials
    {
        public string Наименование_материала { get; set; }
        public string Тип_материала { get; set; }
        public string Изображение { get; set; }
        public decimal Цена { get; set; }
        public double Количество_на_складе { get; set; }
        public double Минимальное_количество { get; set; }
        public int Количество_в_упаковке { get; set; }
        public string Единица_измерения { get; set; }
        public string Описание { get; set; }
    }
}
